Question 3-a

In [4]:
import numpy as np

# The dataset
x = np.array([[64, 29, 580],
     [66, 33, 570],
     [68, 37, 590],
     [69, 46, 660],
     [73, 55, 600]])

# Compute the covariance matrix of data
covar = np.cov(x, rowvar=False)

# Inverse matrix of covariance
inverse_cov = np.linalg.inv(covar)

mahal = []

X = [73, 55, 600]
for data in x:
  dif = np.transpose(X - data)
  res = np.dot(np.dot(dif ,inverse_cov), dif)
  mahal.append(np.sqrt(res))

print("Distances between 5th person and others: \n", mahal)

[[  11.5    34.75   50.  ]
 [  34.75  110.    205.  ]
 [  50.    205.   1250.  ]]
[[ 3.68851865e+00 -1.28214415e+00  6.27308946e-02]
 [-1.28214415e+00  4.58770977e-01 -2.39526742e-02]
 [ 6.27308946e-02 -2.39526742e-02  2.21900278e-03]]
Distances between 5th person and others: 
 [2.7231729013653028, 2.1467921763778732, 2.8179500864718516, 2.7584121116616487, 0.0]


Question 3-b

Euclidean Distance

In [0]:
x = np.array([[64, 29, 580],
     [66, 33, 570],
     [68, 37, 590],
     [69, 46, 660],
     [73, 55, 600]])
    
dist = []

data = [73, 55, 600]

for observation in x:
  
  sub = [a_i - b_i for a_i, b_i in zip(observation, data)]
  
  power = np.power(sub, 2)
  
  dist.append(np.sqrt(sum(power)))

print(dist)
   

[34.0147027033899, 37.8549864614954, 21.18962010041709, 60.802960454241045, 0.0]
